### ISSUE TITLE
安卓11无法安装

### ISSUE THREAD

**Issue by MioDisk** [Nitsuya/DoNotTryAccessibility#1]
类原生安卓11Crdroid

**Comment by Nitsuya** [comment]
A12+, 我晚点看下 其他版本的Server实现差异。

**Comment by Nitsuya** [comment]
大致看了下没啥问题. 已放开 Android 8.1 +

star! star! star!

**Comment by MioDisk** [comment]
> 大致看了下没啥问题. 已放开 Android 8.1 +
> 
> star! star! star!

OK
