### ISSUE TITLE
Error in LSPosed v1.9.3_mod. It works but I can't select the application.

### ISSUE THREAD

**Issue by chkopo** [Nitsuya/DoNotTryAccessibility#2]
![Screenshot_20241010-142243](https://github.com/user-attachments/assets/4621dbb9-2d7b-465d-8faf-0f9d891cb28f)
![Screenshot_20241010-142500](https://github.com/user-attachments/assets/8d255900-48ab-411c-8f71-a45978678a50)
![Screenshot_20241010-142328](https://github.com/user-attachments/assets/a7ce3d9c-9be5-444d-bb7c-0e20f81a1061)
![Screenshot_20241010-142408](https://github.com/user-attachments/assets/73c8a9a9-6d42-41e0-8771-811d439b25f0)

**Comment by Nitsuya** [comment]
~激活模块！重启手机！~
我没有认真查看图片.

**Comment by Nitsuya** [comment]
似乎已经hook上了.  该问题可能需要LSP解决! 
因为开放应用选择可能无法写入配置文件!!

**Comment by ycrichard** [comment]
一样的问题，没法解决。以后都只能用mod版的lsposed了

**Comment by Nitsuya** [comment]
说明不止我一个应用出现问题！
比如这个应用[com.fankes.apperrorstracking]
你可以看看这个应用是否出现一样的问题

**Comment by Nitsuya** [comment]
> 一样的问题，没法解决。以后都只能用mod版的lsposed了

说明不止我一个应用出现问题！
比如这个应用[com.fankes.apperrorstracking]
你可以看看这个应用是否出现一样的问题

**Comment by ycrichard** [comment]
下面的lsposed版本可用，没问题了
https://github.com/JingMatrix/LSPosed/releases
