### ISSUE TITLE
安卓9重启后貌似与shamiko和lsp和zygisknext冲突

### ISSUE THREAD

**Issue by mphin** [Nitsuya/DoNotTryAccessibility#3]
安卓9系统 阿尔法28101，勾选系统框架重启后貌似与shamiko和lsp和zygisknext冲突全部都关闭了。

已尝试更换阿尔法版本，以及LSP模块更换至1.8.6-6712和1.10.1-7115无果。
卸载DoNotTryAccessibility后重启手机shamiko和lsp和zygisknext都正常了。

![photo_2024-12-13_01-03-56](https://github.com/user-attachments/assets/741ba8ce-e530-464c-85a3-56d94422d269)

**Comment by Nitsuya** [comment]
不是一个层面的东西, 按理说不会冲突的.
感觉像是你操作问题, 而且我也没有A9, 自己排查吧.
